### ISSUE TITLE
Share prior training materials/resources on wiki page 

### ISSUE THREAD

**Issue by shapaklyak** [ICPI/Data-Core-Competencies-using-R#1]

**Comment by achafetz** [comment]
created a new [wiki page](https://github.com/ICPI/Data-Core-Competencies-using-R/wiki/Reference-Material) with some initial resources

**Comment by jb3436** [comment]
I added the resources referenced in #8 to the wiki page

**Comment by jb3436** [comment]
I added the link Imran shared in Slack to the wiki page
