### ISSUE TITLE
R Content Lesson plan

### ISSUE THREAD

**Issue by shapaklyak** [ICPI/Data-Core-Competencies-using-R#13]
example lesson plan in R Training Slack group

@shazadahmed10 will pull together content into lesson plan template

**Comment by shazadahmed10** [comment]
Finished the Session 1 lesson plan:

[R Training Session 1 Lesson Plan.docx](https://github.com/ICPI/Data-Core-Competencies-using-R/files/2272075/R.Training.Session.1.Lesson.Plan.docx)

**Comment by shazadahmed10** [comment]
Lesson Plan for Sessions 1 & 2:

[R Training Lesson Plans.docx](https://github.com/ICPI/Data-Core-Competencies-using-R/files/2274947/R.Training.Lesson.Plans.docx)
