### ISSUE TITLE
Identify Trainers/Facilitators for Sessions

### ISSUE THREAD

**Issue by shapaklyak** [ICPI/Data-Core-Competencies-using-R#16]
Potential pool:
--
- Shazad
- Aaron
- Aliyah
- Anu
- Josh
- Travis
- Imran

**Sessions 1 &2**
--
Presenters
- Anu
- Shazad
- Aliyah

Facilitators:
- Yaa
-Abe

Not available for session 1&2: Travis, Aaron, Imran

**Comment by kkale25** [comment]
Presenter (Session 1 and 2) 
- Shazad 
- Aliyah
- Anu 

Facilitators (Session 1 and 2) 
- Anyone in the pool 

Aaron, Travis, Imran (not available for Session 1 and 2)

**Comment by shazadahmed10** [comment]
Abe has agreed to help facilitate
