### ISSUE TITLE
Slidedeck

### ISSUE THREAD

**Issue by shapaklyak** [ICPI/Data-Core-Competencies-using-R#17]

**Comment by shapaklyak** [comment]
@shazadahmed10 please see slide deck template with slides from the pre-training assessment attached.

FYI @anu87  @aliyahwakil @kkale25 

[ICPI R Training_v1.pptx](https://github.com/ICPI/Data-Core-Competencies-using-R/files/2303711/ICPI.R.Training_v1.pptx)

**Comment by shapaklyak** [comment]
also @shazadahmed10 , for further info on the pre-training assessment - @kkale25 did a nice job summarizing this last week in #9

**Comment by shazadahmed10** [comment]
[Session 1.pptx](https://github.com/ICPI/Data-Core-Competencies-using-R/files/2308049/Session.1.pptx)
Session 1 slides here @shapaklyak  !

**Comment by shapaklyak** [comment]
reviewing now

**Comment by shapaklyak** [comment]
@shazadahmed10 @achafetz 
I've made the below edits.  I can't really comment after slide 19 as I don't know the structure of the rest of the training and when you plan to interchange with the script. I am concerned about getting through all the content for session 1 & 2  in the 3 hour block.

Edits:
- deleted violent slide..sorry :)
- consolidated slide 9 & 10 into slide 9 - all skills into one slide
- deleted extra Rstudio slide before Excel
- moved slide 17 to notes on slide 16 on RStudio interface
- added title "IT check" to slide 19, and linked to R Training repo for file download.

[Session.1_en.pptx](https://github.com/ICPI/Data-Core-Competencies-using-R/files/2308104/Session.1_en.pptx)

**Comment by shazadahmed10** [comment]
I will add some slides for Session 2 today to this and repost when I am finished.
