### ISSUE TITLE
Agenda

### ISSUE THREAD

**Issue by shapaklyak** [ICPI/Data-Core-Competencies-using-R#19]
template for agenda 

[ICPI R Training Agenda.docx](https://github.com/ICPI/Data-Core-Competencies-using-R/files/2308238/ICPI.R.Training.Agenda.docx)

**Comment by shapaklyak** [comment]
thanks @shazadahmed10 . Looks good.
Do you think 40minutes is enough to review all the code and explain the concepts for Session 2 (11:30-12:10)?  

fyi @achafetz

**Comment by shazadahmed10** [comment]
@shapaklyak we could go longer than 40min if we find that we are falling behind, and then ask folks to do the independent exercise for Session 2 on their own time. But I think 40 mins might be enough...the topics in Session 2 that will take a long time will be piping and creating new variables. The other topics are straightforward. 

And this is all assuming we get through all of Session 1's topics on time :)

**Comment by shapaklyak** [comment]
ok @shazadahmed10 thanks! Be sure to take your time with Session 1 and the basics then. If you lose the audience on Session 1 trying cover everything but no one is on the same page, then it makes Session 2 difficult for you.

**Comment by kkale25** [comment]
@shazadahmed10 let me know what you need help printing with for tomorrow (agenda, script, etc). I can be in the office early if you need help!
