### ISSUE TITLE
Training certificate? Yes/No? 

### ISSUE THREAD

**Issue by shapaklyak** [ICPI/Data-Core-Competencies-using-R#20]
can we use the layout from the Tableau training and revise for this R training tomorrow? @hessionra do you have the mock up from the Tableau training? Could always print people's names if short on time to handwrite.

**Comment by kkale25** [comment]
Do we have nice cardstock to print them on? If so - should be easy enough to use the same template as the Tableau training. I actually think it may be easier to handwrite people's names and just print a bunch of blank ones so we don't have to worry if someone shows up/doesn't show up last minute.

**Comment by kkale25** [comment]
@hessionra here are the list of names in case you decide to print 

Yaa Obeng-Aduasare

Katya Noykhovich

Tonji Durant 

Audrey Knutson

Kashmira Kale

JP Abellera

Rena Fukunaga

KaeAnne PArris

Shannon Uppaluri

Kimi Sato

Rebecca Hession

Shaylee Mehta

Brittney Shook

Anuli Nwaohiri

Danielle

Katie O'Connor

Lindsay Templin

Tim English

Barbara Ddamulira

Couper Turkewitz

Larry Westerman

Peter Minchella

Erin Rottinghaus

Tat'Yana Kenigsberg

Kristin Roha

James Houston

Edward Vallejo

Michelle Li

Dorothy Lee

**Comment by hessionra** [comment]
Done, with blank extras in case there are any last minute registrations and/or visitors!

**Comment by kkale25** [comment]
Thanks Rebecca!
