### ISSUE TITLE
Slack channel for remote attendees? yes/no? #rtraining 

### ISSUE THREAD

**Issue by shapaklyak** [ICPI/Data-Core-Competencies-using-R#21]
do we want attendees to use slack to communicate any errors  - would it be easier rather than switching back and forth between adobe connect? I can help monitor and triage questions if needed.
thoughts?

**Comment by kkale25** [comment]
Would they have to download slack, create a profile, etc. etc.? Or is a web-based version they can use easily? May eat into the training time if people don't already have it.

**Comment by shazadahmed10** [comment]
hmmm...good question...my inclination is to have participants utilize the slack channel after the training...so anyone in the community can help them when needed. 
For the training, I think the chat box in adobe would suffice...we are hoping not too many ppl will be virtual anyway. 
So, my suggestion is that at the end of the training, we suggest that folks use the slack channel to seek help

**Comment by shapaklyak** [comment]
works for me @kkale25 @shazadahmed10

**Comment by kkale25** [comment]
Sounds good. Just be sure to let the participants know about the Slack channel and point them to where/how to get it.
