### ISSUE TITLE
Send Reminder email about R Training Evaluation 

### ISSUE THREAD

**Issue by shapaklyak** [ICPI/Data-Core-Competencies-using-R#24]
As of date - 11 out of 30 registered participants completed the evaluation. What are the final attendance #s?

**Comment by kkale25** [comment]
Hi @hessionra - could you share the final names/number of total participants from the sign-in sheet? 

Also - could we send the below email to the final participants to remind them take the post-training evaluation by COB tomorrow? Thanks so much!

Subject: Please Complete: ICPI R Training Post-Evaluation Survey
To: All attendees of the R Training on 8/23

Hello ICPI R Training Participants,

Thank you again for attending the R Training on Thursday, 8/23. You can find the materials from the training on [GitHub](https://github.com/ICPI/R-Training). We are also working on recording the sessions and sharing them  in the coming weeks.

In the meantime, it is crucial you complete this quick post-training survey. It will take just a few minutes of your time and provide invaluable insight into improving future sessions. 

Link to survey: https://goo.gl/forms/ztSPdez5txyVmbFI3

Thank you,
ICPI

**Comment by shapaklyak** [comment]
looks good. you could ask in the email for participants to note in the comments whether or not they stayed for the afternoon session.

**Comment by kkale25** [comment]
We made a list of those who did. @hessionra has it! No need to ask :)

**Comment by shapaklyak** [comment]
fyi...they don't have to put their name down in the evaluation (it's optional)...so you won't know who attended the PM session and break down the data in that way.
