### ISSUE TITLE
Invite Language for R Training

### ISSUE THREAD

**Issue by kkale25** [ICPI/Data-Core-Competencies-using-R#33]
Hi @hessionra - could you please send out the invites to the attendees of the Session 3/4 of the R Training? Please include everyone from the original Sessions 1/2 invitation and those listed here: https://github.com/ICPI/Data-Core-Competencies-using-R/issues/32

Date: 10/18 
Time: 10AM - 5PM
Location: Shared Conference Room A/B
Event Name: ICPI R Training: Sessions 3 and 4
Text: 
Dear all,

Please join us on Thursday, 10/18 from 10AM - 5PM and Friday, 10/19 from 9AM - 1PM for the ICPI R Training: Sessions 3 and 4. These sessions are the next ones in the R Training Series and will cover topics such as:
- Transposing
- Calculated indicators
- Merging with external datasets
- ICPI Utilities 
- Visualizations (mapping, bar graphs)

To attend virtually, please use the following:
Conference Line: (877) 336.1839
Access Code: 5428682
Adobe Connect: REBECCA CAN YOU PLEASE CREATE AN ADOBE CONNECT LINK?

All participants must fulfill the following requirements (please complete the **entire** list before training day): 

1. Have R and R Studio installed on their computers
- Download R [here](https://cran.cnr.berkeley.edu/)
- Download R Studio [here](https://www.rstudio.com/products/rstudio/download/)

2. Review recordings of Sessions 1 and 2 (if you did not attend Sessions 1 and 2, you **must** review these recordings and complete the exercises to be eligible to attend Sessions 3 and 4)
- [Session 1 recording](https://pepfar.adobeconnect.com/pk8v8zf33x32/)
- [Session 2 recording](https://pepfar.adobeconnect.com/p9o8qs2661dh/)
- Files needed to complete Sessions 1 and 2 exercises can be found [here](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC%2DHQ%2Ficpi%2FShared%20Documents%2FTrainings%2FICPI%20R%20Training%20August%202018&FolderCTID=0x01200080CC6F83D1766F4D9E3497D4529EC74A&View=%7B94C838B2%2DE166%2D4122%2DB8B4%2D7BEB9E1BC12B%7D&InitialTabId=Ribbon%2EDocument&VisibilityContext=WSSTabPersistence)

3. Submit the Culmination Exercises for both Session 1 and Session 2 to icpi@state.gov by Wednesday, 10/17. You will not receive a training completion certificate without submitting these to ICPI!
- Files needed to complete Culmination Exercises can be found [here](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC%2DHQ%2Ficpi%2FShared%20Documents%2FTrainings%2FICPI%20R%20Training%20August%202018&FolderCTID=0x01200080CC6F83D1766F4D9E3497D4529EC74A&View=%7B94C838B2%2DE166%2D4122%2DB8B4%2D7BEB9E1BC12B%7D&InitialTabId=Ribbon%2EDocument&VisibilityContext=WSSTabPersistence)

Please email icpi@state.gov if you have any questions.

Thank you,
ICPI
------------------------
Date: 10/19 
Time: 9AM - 1PM
Location: Africa Conference Room
Event Name: ICPI R Training: Sessions 3 and 4
Text: 
Dear all,

Please join us on Thursday, 10/18 from 10AM - 5PM and Friday, 10/19 from 9AM - 1PM for the ICPI R Training: Sessions 3 and 4. These sessions are the next ones in the R Training Series and will cover topics such as:
- Transposing
- Calculated indicators
- Merging with external datasets
- ICPI Utilities 
- Visualizations (mapping, bar graphs)

To attend virtually, please use the following:
Conference Line: (877) 336.1839
Access Code: 5428682
Adobe Connect: REBECCA CAN YOU PLEASE CREATE AN ADOBE CONNECT LINK?

All participants must fulfill the following requirements (please complete the **entire** list before training day): 

1. Have R and R Studio installed on their computers
- Download R [here](https://cran.cnr.berkeley.edu/)
- Download R Studio [here](https://www.rstudio.com/products/rstudio/download/)

2. Review recordings of Sessions 1 and 2 (if you did not attend Sessions 1 and 2, you **must** review these recordings and complete the exercises to be eligible to attend Sessions 3 and 4)
- [Session 1 recording](https://pepfar.adobeconnect.com/pk8v8zf33x32/)
- [Session 2 recording](https://pepfar.adobeconnect.com/p9o8qs2661dh/)
- Files needed to complete Sessions 1 and 2 exercises can be found [here](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC%2DHQ%2Ficpi%2FShared%20Documents%2FTrainings%2FICPI%20R%20Training%20August%202018&FolderCTID=0x01200080CC6F83D1766F4D9E3497D4529EC74A&View=%7B94C838B2%2DE166%2D4122%2DB8B4%2D7BEB9E1BC12B%7D&InitialTabId=Ribbon%2EDocument&VisibilityContext=WSSTabPersistence)

3. Submit the Culmination Exercises for both Session 1 and Session 2 to icpi@state.gov by Wednesday, 10/17. You will not receive a training completion certificate without submitting these to ICPI!
- Files needed to complete Culmination Exercises can be found [here](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC%2DHQ%2Ficpi%2FShared%20Documents%2FTrainings%2FICPI%20R%20Training%20August%202018&FolderCTID=0x01200080CC6F83D1766F4D9E3497D4529EC74A&View=%7B94C838B2%2DE166%2D4122%2DB8B4%2D7BEB9E1BC12B%7D&InitialTabId=Ribbon%2EDocument&VisibilityContext=WSSTabPersistence)

Please email icpi@state.gov if you have any questions.

Thank you,
ICPI

**Comment by shapaklyak** [comment]
@kkale25 @hessionra @jb3436 do we want to send this out to all who received the initial invite, in case there are a few stragglers would like to join?

**Comment by kkale25** [comment]
Yep - it's meant to go to everyone who's received the invite originally plus the others who've RSVPed.

**Comment by hessionra** [comment]
@kkale25 sent invites 10/9!
