### ISSUE TITLE
PVA First Session Topics/Videos

### ISSUE THREAD

**Issue by shazadahmed10** [ICPI/Data-Core-Competencies-using-R#39]
- Navigate the RStudio interface
- Load R packages
- Import .txt or csv datasets (drop down menu import, explicitly demo read_tsv, then verbally mention read_csv. `ICPIutilities `might be too complicated due to having to show how to download, explain, extra steps. Is `ICPIutilities` still being actively updated? ensure variable types are correct, show in argument
- explore datasets (str function, previewing dataset in global environment, comment on MSD structure being semi wide/long, quick examples of other datasets)
- sort variables (dates, alphabetically) (low priority) 
- subset (filter by rows) 
- delete variables
- Export datasets into .txt or csv
- data management methods & R Projects  (right way to open and close RStudio; work flow basics, cover the basics) 

Later Sessions?:
- talk about dataset structure theory (long, wide)?
- updating R package (advanced topic) 
- how to maintain R scripts (advanced)
- utilizing Jupyter notebooks for sharing/annotating R scripts

-if a topic is a natural extension, then roll out with initial content
-if standalone advanced, then rollout later

**Comment by shazadahmed10** [comment]
Mtg 8/19:

- send ppt to Alex
- Alex to look at old material to re-familiarize himself with the content already created
- Jessica to lead creation of videos: establishing process and roles for generating the 4-6 minute videos
- Jessica to create word doc on how to record using Ppt screen record feature

**Comment by jessihandy** [comment]
I figured instead of a word document, I'd show how to do a screen recording by actually doing it. Hopefully this helps!

[Screen_Recording_usingPPTx.pptx](https://github.com/ICPI/Data-Core-Competencies-using-R/files/5098834/Screen_Recording_usingPPTx.pptx)

**Comment by jessihandy** [comment]
Proposed assignments/workflow. 
[R_S1_Assignments.docx](https://github.com/ICPI/Data-Core-Competencies-using-R/files/5103812/R_S1_Assignments.docx)

**Comment by jessihandy** [comment]
Scripts and draft R script for sessions 2-4. Please review and edit by 9/4 so I/whoever can have the following week to produce the ppt/videos by 9/10. 
[R_S1_Scripts_JH.zip](https://github.com/ICPI/Data-Core-Competencies-using-R/files/5136598/R_S1_Scripts_JH.zip)

**Comment by jessihandy** [comment]
Handed off for PRIME review 9/14
