### ISSUE TITLE
Develop core competencies

### ISSUE THREAD

**Issue by shapaklyak** [ICPI/Data-Core-Competencies-using-R#5]

**Comment by achafetz** [comment]
Here are the core competencies as I see them:

1. principles of [tidy data](https://vita.had.co.nz/papers/tidy-data.pdf)
2. reproducibility/transparency
3. workflow basics
4. data visualizing (basics) 
5. data tranformation (filtering, selecting, mutating)
6. conditions - if/ifelse statements
7. summarizing data
8. merging datasets
9. iterating
10. working with string data

**Comment by jaliasd** [comment]
I would just add something (or include this inside one of the above (#7)) something about exploring data; ie being able to tabulate different subsets of results based on conditions. Like `tab var1 var1 if var3==x` in stata

**Comment by achafetz** [comment]
Next steps:
  - flesh out above competencies  in [wiki](https://github.com/ICPI/Data-Core-Competencies-using-R/wiki/Core-Competencies), issue #6
  - group competencies for training sessions
  - develop training curriculum

 
moved to [wiki](https://github.com/ICPI/Data-Core-Competencies-using-R/wiki/Core-Competencies)
